### ISSUE TITLE
Blocked by CORS policy error

### ISSUE THREAD

**Issue by PenguinM** [CyrilCommando/SankakuCacher#11]
I encountered this error recently. 
Protocol inconsistency? 
But I'm sure it is https.
![Snipaste_2023-11-03_09-06-18](https://github.com/CyrilCommando/SankakuCacher/assets/66694792/7b246201-dc9e-4e58-b6d5-a026d3467660)

**Comment by CyrilCommando** [comment]
OK I think I fixed everything. Redownload from master & make sure to follow [this](https://youtu.be/bRLvWh02dfk) or extract the contents into your existing extension folder
