### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by PenguinM** [CyrilCommando/SankakuCacher#12]
![Snipaste_2024-04-26_17-02-43](https://github.com/CyrilCommando/SankakuCacher/assets/66694792/27fdf9d2-8ecb-4ab6-9276-fdce773990e0)
new type -0-

**Comment by CyrilCommando** [comment]
Hi Peng. Yeah it's been busted for about a month. They keep changing the URL scheme of the site, so stuff keeps breaking. I got Mass Download working again, which is probably the feature most of us are using let's be honest..
I don't have time to fix the rest though. I think I'll drop a lot of the site specific features like resizing icons and favorite functions, and focus on making this a downloader, for all the other Boorus too
Fix will be uploaded to master branch, and Firefox branch also

**Comment by PenguinM** [comment]
That’s true. I only used the download function xd and now it works again.
In any case, this is the best downloader I have ever used, thank you for your efforts!
