### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by fluffyjin** [CyrilCommando/SankakuCacher#6]
Seems that the link generates with v.sankaku instead of the usual s.sankaku which causes this issue. That's all I've been able to deduce. Thanks for checking it out

**Comment by fluffyjin** [comment]
Seems like its happening with all links that now have expiration and tokens extended to their links. Im analyzing it but not sure what to implement to overcome this situation.

**Comment by fluffyjin** [comment]
After some intense research, I've tried working with CORS with the crossOrigin thingy, no luck. Waiting for your guidance sensei. Your JS comments are pretty fun to read lol

**Comment by CyrilCommando** [comment]
Gonna chalk this one up to the site being shitty. As I was in the process of fixing it, it seemed to have just fixed itself. It looks like they may have changed CDNs. This is obviously a volatile issue, so I'll keep this open. Let me know if it's still broken on your end.

**Comment by fluffyjin** [comment]
That's awfully strange lol. It did fix itself for now like you've stated. Thanks for checking out the problem. It's about time this site is changing CDNs.

**Comment by CyrilCommando** [comment]
One small issue is present still - Images viewed through Preview won't add to the menu. I fixed it on the latest version.

**Comment by fluffyjin** [comment]
Sweet, I want to contribute to this project. It's one I personally use and love. I'll start looking into javascript more seriously.

**Comment by fluffyjin** [comment]
The site is generally faster now. The issue is once again occurring. Wonder what they are up to again. I heard they were migrating materials to a new host. Not 100% sure.

**Comment by CyrilCommando** [comment]
>I heard they were migrating materials to a new host. 

I sure hope that’s the case. Some of the images hosted on the new service (referred to as “BunnyCDN”, apparently..) have a much more functional CORS setup. It would’ve meant much less headache had it have been that way when I first made the preview function ages ago..
As for the issue, it seems to be fixed for me. How about on your end?

**Comment by fluffyjin** [comment]
Hello, yeah it seems like it comes and goes. Kinda resolves itself for some reason. Thanks for getting back
